### ISSUE TITLE
Making the Counter Animation for statistics on Home page work only once on scroll.

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#12]
Just visit the [Codepeak Website](https://www.codepeak.tech/) and scroll down to the Past Statistics section.
You will be able to figure out that the Number Counter Animation is working again and again on scroll unlike other animations.
That looks pretty wierd. Help us remove that.

![20211208_184947](https://user-images.githubusercontent.com/76230753/145215333-69e99802-9123-487d-8c02-4d8feccfa0e3.jpg)

**Comment by chandrashekar27** [comment]
I'd like to work on this issue.

**Comment by KartuzGupta** [comment]
> I'd like to work on this issue.

I have assigned you the issue. You can work on it.

**Comment by KartuzGupta** [comment]
> I'd like to work on this issue.

Any updates @chandrashekar27

**Comment by chandrashekar27** [comment]
> > I'd like to work on this issue.
> 
> Any updates @chandrashekar27

I'm trying but I've not been able figure out a working approach yet. (I tried using a `useState` object to check if the `CountUp` animation already rendered once, but this method didn't work). Can you please suggest any other ways to approach this?

**Comment by KartuzGupta** [comment]
> > > I'd like to work on this issue.
> > 
> > 
> > Any updates @chandrashekar27
> 
> I'm trying but I've not been able figure out a working approach yet. (I tried using a `useState` object to check if the `CountUp` animation already rendered once, but this method didn't work). Can you please suggest any other ways to approach this?

Tbh I am also unable to resolve this issue. I tried a lot but was unsuccessful :"). Keep trying !!

**Comment by KartuzGupta** [comment]
> > > I'd like to work on this issue.
> > 
> > 
> > Any updates @chandrashekar27
> 
> I'm trying but I've not been able figure out a working approach yet. (I tried using a `useState` object to check if the `CountUp` animation already rendered once, but this method didn't work). Can you please suggest any other ways to approach this?

Any updates??

**Comment by prathamiitp** [comment]
I would like to try this issue.

**Comment by KartuzGupta** [comment]
Okay try

**Comment by KartuzGupta** [comment]
Closing issue. Issue Resolved!! Great work @prathamiitp
