### ISSUE TITLE
Better UI for Leaderboard Page

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#13]
The [Leaderboard Page](https://www.codepeak.tech/leaderboard) does not look up to the mark.
Would love to see your designs for this page.

Points will depend upon your design.

**Comment by nguyenhung15913** [comment]
Hi Can I work on this issue?

**Comment by KartuzGupta** [comment]
> Hi Can I work on this issue?

You can work on the issue. 
You can send your designs on the [discord server](https://discord.gg/xhQ9N9Z3jc) (for both laptop and mobile view)
Feel free to ask any doubts.

**Comment by nguyenhung15913** [comment]
Hi which channel should I give the design thanks

**Comment by KartuzGupta** [comment]
> Hi which channel should I give the design thanks

You just create a pull request. We will review it.

**Comment by nguyenhung15913** [comment]
ok thanks, I guess i will craete a pull request first

**Comment by KartuzGupta** [comment]
> ok thanks, I guess i will craete a pull request first

Any updates??

**Comment by KartuzGupta** [comment]
Issue is open for contribution

**Comment by shmiitg** [comment]
I managed to solve the issue. If you like the design I will create a pr
![Screenshot (336)](https://user-images.githubusercontent.com/70333141/147491103-7e3fcd1b-e0b1-499b-b21a-87406bf7f6ec.png)
![Screenshot (337)](https://user-images.githubusercontent.com/70333141/147491128-001c713a-0d63-405b-a078-c8987861241c.png)
![Screenshot (338)](https://user-images.githubusercontent.com/70333141/147491154-c1004d47-ff67-4705-a235-ed2372e226e0.png)
