### ISSUE TITLE
Adding Search Facility in Leaderboards Page

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#16]
Adding a search facility in [Leaderboards Page](https://www.codepeak.tech/leaderboard) where one can search their score and position using to their github handle. 

On the top there should be Search bar where participant can write their Name and the Scores and Position corresponding to the name is shown. You can refer to [Projects Page](https://www.codepeak.tech/project) for ideas.

**Comment by Code-Aditya-14** [comment]
I would like to work on this issue.

**Comment by VishalIITP** [comment]
> I would like to work on this issue.

The issue has been assigned to you.
