### ISSUE TITLE
Highlighting the Register option in the Navbar when on Student Registration Form or Mentor Registration Form

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#19]
When we are Register Page, the Register option on navbar is highlighted.
![CODEPEAK - Google Chrome 10-12-2021 16_10_42](https://user-images.githubusercontent.com/72855990/145561342-2a90f0b9-ba06-485c-afe5-3190bdbc221e.png)
But when we go to Participant Registration Form or Mentor Registration Form, it no longer remains highlighted.
![CODEPEAK - Google Chrome 10-12-2021 16_10_36](https://user-images.githubusercontent.com/72855990/145561484-886b0365-d2ec-4976-aea0-7a2c44dc8f6e.png)

**Comment by ArchismanKarmakar** [comment]
I want to work, please assign me, also as my exams are coming so I may take some extra time

**Comment by VishalIITP** [comment]
> I want to work, please assign me, also as my exams are coming so I may take some extra time

You have been assigned the issue

**Comment by ArchismanKarmakar** [comment]
> > I want to work, please assign me, also as my exams are coming so I may take some extra time
> 
> You have been assigned the issue

updated the code

**Comment by KartuzGupta** [comment]
Issue rectified by @ArchismanKarmakar . Nice work.
