### ISSUE TITLE
Adding Campus Ambassadors form

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#24]
Making a CA form which opens on clicking the existing button.
Information to be asked:
1)Name
2)Email
3)College Name
4)College ID
5)Phone Number

**Comment by padmaja2305** [comment]
I would like to work on this issue

**Comment by KartuzGupta** [comment]
> I would like to work on this issue

Cool ! assigning it to you.

**Comment by KartuzGupta** [comment]
Done #24
