### ISSUE TITLE
UI for Profile page for Mentor

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#27]
Show the following details:
1)Name
2)Github Id
3)Projects
4)Email
5)Phone
6)College

Refer to the participant profile page.

**Comment by prathamiitp** [comment]
I would like to work on this issue.

**Comment by KartuzGupta** [comment]
> I would like to work on this issue.

Assigning this issue to you.

**Comment by shmiitg** [comment]
I would like to work on this
