### ISSUE TITLE
UI for Edit Profile Form for participants

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#28]
Details that can be edited:
1)Name
2)Email
3)Github ID
3)College Name
4)Phone Number
5)Password

**Comment by padmaja2305** [comment]
I would like to work on this issue

**Comment by KartuzGupta** [comment]
> I would like to work on this issue

Okay assigning it to you.

**Comment by Sanath91009** [comment]
Is this issue completed ? If not i am interested.
