### ISSUE TITLE
UI for Edit Profile Form for Mentor

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#34]
Details to be edited:
1)Name
2)Github ID
3)Projects
4)Email
5)Phone Number
6)College
7)Password

Refer Edit Profile page of Participant

**Comment by prathamiitp** [comment]
I would like to work on this issue.

**Comment by KartuzGupta** [comment]
> I would like to work on this issue.

Okay assgning it to you

**Comment by KartuzGupta** [comment]
Reviewed your PR and merged it .awarding you points

**Comment by Sanath91009** [comment]
claim
