### ISSUE TITLE
Dashboard for mentors for marking the participants

### ISSUE THREAD

**Issue by padmaja2305** [VishalIITP/CodepeakSuperDuper#35]
We can create a form for the mentors where they will fill in the GitHub id and score of the participants.

**Comment by KartuzGupta** [comment]
Yaa ryt, we should add that. Would you like to work on the issue??

**Comment by padmaja2305** [comment]
yeah, sure! I would like to try it

**Comment by KartuzGupta** [comment]
> yeah, sure! I would like to try it

Okay assigning this issue to you
