### ISSUE TITLE
Showing a loading icon on the leaderboard page till data is not fetched

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#40]
On opening the Leaderboard page for few seconds such a page is seen:
![CODEPEAK - Google Chrome 20-12-2021 01_10_03](https://user-images.githubusercontent.com/72855990/146688506-faa6e1c3-f2f3-49f1-966f-f3b08f4c871c.png)

This occurs because it takes some time for the data to be fetched from G-sheet. We want to display some loading icon till the data is not fetched.

**Comment by shmiitg** [comment]
can i take this issue?

**Comment by shmiitg** [comment]
https://user-images.githubusercontent.com/70333141/146957076-0d5d361f-6a58-4b6f-9954-42b40ab1c5ee.mp4

Please see if this works. Should I create a pr?
