### ISSUE TITLE
Facility for Adding and editing projects 

### ISSUE THREAD

**Issue by KartuzGupta** [VishalIITP/CodepeakSuperDuper#42]
For adding project.
Requirements:
1)Name
2)Link
3)Description
4)Tech used
5)Tags

**Comment by padmaja2305** [comment]
I would like to work on this issue

**Comment by KartuzGupta** [comment]
> I would like to work on this issue

Okay. Assigning it to you

**Comment by KartuzGupta** [comment]
PR merged!!
