### ISSUE TITLE
leaderboard is not sorted in accordance with the participant score

### ISSUE THREAD

**Issue by shmiitg** [VishalIITP/CodepeakSuperDuper#47]
![Screenshot (329)_LI](https://user-images.githubusercontent.com/70333141/147402588-7c2a9e89-e3c7-427b-8d50-2a1339d712a2.jpg)
The leaderboard is rendered in the same order as in the google doc sheet. We can sort the leaderboard after fetching the data and then display the final leaderboard

**Comment by shmiitg** [comment]
I would like to correct this once you approve the issue

**Comment by KartuzGupta** [comment]
this is the problem of g-sheets. it sorts itself after certain interval.
