### ISSUE TITLE
File structure NodeJs in backend folder

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodepeakSuperDuper#50]
In the backend folder you have to setup the file structure for NodeJs backend for [Codepeak](https://www.codepeak.tech)

**Comment by shmiitg** [comment]
I would like to work on this issue. I need make a folder named node-js and put config, routes, etc there right?

**Comment by VishalIITP** [comment]
> I would like to work on this issue. I need make a folder named node-js and put config, routes, etc there right?

Yes

**Comment by shmiitg** [comment]
ok you can assign me this issue

**Comment by VishalIITP** [comment]
@shmiitg great you can work on the issue, assigned to you

**Comment by shmiitg** [comment]
@VishalIITP  Thanks for assigning. I created this folder structure
![Screenshot (347)](https://user-images.githubusercontent.com/70333141/147580052-60611cca-68d7-4f30-83eb-35281818c614.png)
I included the required code in .gitigore file. I am ready to make a pr but I already have a existing pr. Once that is reviewd i will create a pr for this issue

**Comment by VishalIITP** [comment]
Good work @shmiitg  assigned you 5 points
