### ISSUE TITLE
Create Login API using Node Js in Backend

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodepeakSuperDuper#53]
1. Login of both mentors and Participants should be according to our login frontend in the http://localhost:3000/login
2. Both Mongo DB and SQL are preferred you can comment which database suits you, we(mentors) will decide accordingly

![Screenshot from 2021-12-31 00-50-38](https://user-images.githubusercontent.com/76230753/147782082-acc94169-694c-4843-9d50-84373fbe91a1.png)

**Comment by shmiitg** [comment]
I would like to work on this. I will prefer mongodb database.

**Comment by KartuzGupta** [comment]
> I would like to work on this. I will prefer mongodb database.

Sorry couldn't reply you.
Assigning it to you.
