### ISSUE TITLE
Connect login API to React js Frontend

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodepeakSuperDuper#54]

**Comment by aritroCoder** [comment]
I want to work on this, please give some guidelines how to start and what you exactly want

**Comment by mayuri-dhote** [comment]
Hello @VishalIITP I would like to take this issue.
please assign to me.

**Comment by shmiitg** [comment]
I would like to work on this

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by shmiitg** [comment]
@VishalIITP I created a pr for other  login options. You can assign me this now
