### ISSUE TITLE
Create sign up(Registration) API using Node Js Backend

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodepeakSuperDuper#55]
Register API

**Comment by VishalIITP** [comment]
Both Mongo DB and SQL are preferred you can comment which database suits you we will decide accordingly

**Comment by letsintegreat** [comment]
I'd like to work on this issue, I will prefer mongoDB.

**Comment by VishalIITP** [comment]
> I'd like to work on this issue, I will prefer mongoDB.
Great, you can proceed, we would be using mongoDB as our database.
