### ISSUE TITLE
Connect Sign up API to React Js Frontend

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodepeakSuperDuper#56]

**Comment by sauravrajleaf** [comment]
I would like to work on this. Please assign this to me.

**Comment by VishalIITP** [comment]
> I would like to work on this. Please assign this to me.

Assigned to you, you can work after the backend API is created

**Comment by sauravrajleaf** [comment]
okay. Thanks XD

**Comment by letsintegreat** [comment]
@sauravrajleaf Backend is ready! You will need to send a POST req to `/signup/mentor`, `/signup/student` or `/signup/ca`.

### Mentor:

##### Required parameters:

- email
- password
- password2
- firstName
- secondName
- phone
- college_name
- github_url
- projects_url

##### Optional parameters:

- gitlab_url
- refferal_code

### Student:

##### Required parameters:

- email
- password
- password2
- firstName
- secondName
- phone
- college_name
- github_url

##### Optional parameters:

- college_id
- gitlab_url
- refferal_code

### CA:

##### Required parameters:

- email
- password
- password2
- name
- phone
- college_name
- college_id

##### Optional parameters:

*none.*


-------

Also, there are no fields to enter password and confirm password as of now, you will have to add them.

-------

@VishalIITP If you think any parameter should be made required or optional, PLMK.

**Comment by sauravrajleaf** [comment]
@letsintegreat Thanks for the information. I will sure check it out & start working on the connection.

**Comment by VishalIITP** [comment]
> @letsintegreat Thanks for the information. I will sure check it out & start working on the connection.
Are you worked on it

**Comment by letsintegreat** [comment]
@VishalIITP as it is the last day, if no one's working on it, I'd like to work.

**Comment by VishalIITP** [comment]
> @VishalIITP as it is the last day, if no one's working on it, I'd like to work.

Yes sure assigned to you
