### ISSUE TITLE
UI for Profile page for Participants

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodepeakSuperDuper#6]
It should match the existing design of [codepeak-website](https://www.codepeak.tech)
Ideas are welcomed points will be allotted based on your creativity or if any part of your design is selected.
Multiple people can contribute to this issue.
Design should be in accordance with the g-form filled for registrations.

**Comment by padmaja2305** [comment]
I would like to work on this issue

**Comment by KartuzGupta** [comment]
> I would like to work on this issue

Okay. Assigning it to you

**Comment by Sanath91009** [comment]
claim

**Comment by aritroCoder** [comment]
I have created a design please check 

https://user-images.githubusercontent.com/92646038/147564603-c62467df-2c1a-4c05-bbaf-1de56d6d18a5.mp4

**Comment by KartuzGupta** [comment]
Move the profile icon to the left of "Welcome John Smith" and remove 'name' from the details. Make profile icon small for small screen.

**Comment by aritroCoder** [comment]
> Move the profile icon to the left of "Welcome John Smith" and remove 'name' from the details. Make profile icon small for small screen.

Yes, I have done that

**Comment by aritroCoder** [comment]
https://user-images.githubusercontent.com/92646038/147732980-564c1f35-0386-4e56-a18d-a4865d894d0d.mp4

**Comment by aritroCoder** [comment]
@KartuzGupta @VishalIITP  please review the PR
