### ISSUE TITLE
Incompatibility of login and register API.

### ISSUE THREAD

**Issue by letsintegreat** [VishalIITP/CodepeakSuperDuper#62]
As login and register API was implemented by different persons, there's a discrepancy here.

Right now mentor, student, and CA are required to send POST requests to 3 different URLs in order to log in. Whereas, while implementing the registering feature, I have linked their post to their email address.

So, all three of them can actually send POST request to the same URL to log in, and after they are logged in, we can use `user.post` to check if they are mentor, student or CA.

**Comment by VishalIITP** [comment]
@letsintegreat great work, awarded you 10 points(5+5). Keep it up!!
